<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HTCLT1474" failures="1" tests="6" name="Account" time="64.57" errors="0" timestamp="2023-07-19T13:59:32 IST">
  <testcase classname="Test.Account_Scenario" name="Login_Salesforce_page" time="0.147"/>
  <testcase classname="Test.Account_Scenario" name="Homepage" time="8.945"/>
  <testcase classname="Test.Account_Scenario" name="Account_Layouts" time="22.017"/>
  <testcase classname="Test.Account_Scenario" name="ShippingAddress_checkbox" time="17.874"/>
  <testcase classname="Test.Account_Scenario" name="Address_compare" time="7.281"/>
  <testcase classname="Test.Account_Scenario" name="Dependency_Filed" time="5.045">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.Account_Scenario.Dependency_Filed(Account_Scenario.java:151)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Dependency_Filed -->
</testsuite> <!-- Account -->
